### PR TITLE
Encrypt and store passphrase locally.

### PR DESCRIPTION
**Pull request by tuanta**
This new pull request has been fully replaced for the old one #89 . Please review and merge it.
Now I will see how to add a new option into zimlet preference for users to select if they would like to store encrypted passphrase locally along with private key.

### CODE REVIEW

**Comment by barrydegraaff** [comment]
You can take a look at tk_barrydegraaff_zimbra_openpgp.settings['auto_decrypt'], as an example on how to have a user setting.

This one should default to server storage, so existing users are not bothered with this change.

Then after this is complete, we can make a cos setting to force it to local store

**Comment by barrydegraaff** [comment]
in the constructor you can check if the pass is on the server:
tk_barrydegraaff_zimbra_openpgp.privatePassCache='';
should be
tk_barrydegraaff_zimbra_openpgp.privatePassCache=(this.getUserPropertyInfo("zimbra_openpgp_privatepass").value ? this.getUserPropertyInfo("zimbra_openpgp_privatepass").value : '')

And then in localStorageSave add an if statement that checks the user setting server/local store and deal with it accordingly.

**Comment by barrydegraaff** [comment]
Also on line 1274:
      var success = privKey.decrypt(passphrase);
can not work, since you renamed passphrase variable

**Comment by tuanta** [comment]
> You can take a look at tk_barrydegraaff_zimbra_openpgp.settings['auto_decrypt'], as an example on how to have a user setting.
> This one should default to server storage, so existing users are not bothered with this change.
Thanks. I will try this way.

However, now I want to deploy a test to my Zimbra test system (using 8.6-P2) to propose a better pull request. The zimlet did not work with this error message in Firefox console:
"SyntaxError: missing ; before statement       tk_barrydegraaff_zimbra_openpgp.js:1204:219"
I checked the code line number 1204. It seems OK.

@barrydegraaff, have you got any ideas?

**Comment by tuanta** [comment]
Seems I am going a wrong way :(
I should keep the old statements to store passphrase at server side then add " if " + other statements to store it at client side.
Of course, an additional parameter (e.g. "store_passphrase_locally") should be added as well.
I will redo all my work this new way in the evening. Please discard this pull request.

**Pull request closed without merging**
