### PR TITLE
Add public key details into Magage Keys dialog

### PR DESCRIPTION
**Pull request by tuanta**
This is the first initial hacks to show public key details (UserID, FingerPrint and Created) under each public key in Manage Keys dialog.
Please kindly accept my pull request and let me know if we need to show any other details.

Btw, I also did shorten the code to show the list of public keys (using a 'for' loop).

### CODE REVIEW

**Comment by barrydegraaff** [comment]
looking good, will test this tomorrow.

Can you also add the `key length`, as so the user can determine if an unsafe key (< 1024 for example) is used?

Thanks a lot!

**Comment by barrydegraaff** [comment]
also, a bit naggy, but I indent with 3 spaces, not with tabs :-p

**Comment by tuanta** [comment]
> also, a bit naggy, but I indent with 3 spaces, not with tabs :-p

@barrydegraaff: thanks, I will change it. and also, add the key length info.

**Comment by tuanta** [comment]
Sorry, I can not find an attribute (similar to primaryKey.fingerprint) which stores keyLength.
Have you got any ideas?

**Comment by barrydegraaff** [comment]
The answer is somewhere in here:
https://github.com/openpgpjs/openpgpjs/blob/master/src/packet/public_key.js

/**
 * Returns bit size of key
 * @return {int} Number of bits
 */
PublicKey.prototype.getBitSize = function () {
  return this.mpi[0].byteLength() * 8;
};

Not sure how to invoke this though, I am asking it on the mailing list.

**Comment by barrydegraaff** [comment]
Thanks Pawel!
@tuanta can you add this?

Date: Thu, 26 Feb 2015 13:44:27 +0100

**Comment by tuanta** [comment]
@barrydegraaff : yes, I will do it.

**Pull request merged**
