### PR TITLE
Store private key passphrase locally

### PR DESCRIPTION
**Pull request by tuanta**
Please review all changes before merging into your master branch. Or you should merge/create a new branch first.
This hack should be improved and tested more.
Please feel free to improve it or just request me to do more things.

### CODE REVIEW

**Comment by barrydegraaff** [comment]
Can you make this a optional feature? So user can select the option to store on server OR use local storage?

**Comment by barrydegraaff** [comment]
Also, can you make a clean fork and commit your changes in that? Merging 47 commits for this, isn't optimal.

**Comment by tuanta** [comment]
Ok, I will make a new branch.

**Comment by tuanta** [comment]
Closing it. I will propose another pull request later.

**Pull request closed without merging**
